/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mynor.analizadorsintactico.vista;

import com.mynor.analizadorsintactico.lexer.Lexer;
import com.mynor.analizadorsintactico.lexer.TipoToken;
import com.mynor.analizadorsintactico.lexer.Token;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.undo.UndoManager;

/**
 *
 * @author mynordma
 */
public class FramePrincipal extends javax.swing.JFrame {

    private String rutaActual = "";
    private String rutaAbsolutaActual = "";
    private boolean cambiosSinGuardar = false;
    private UndoManager undoManager;
    private final ArrayList<Token> tokens;
    private final ArrayList<Token> errores;
    private boolean hayErrores = false;
    
    public FramePrincipal() {
        initComponents();
        setTitle("Analizador Sintáctico");
        outputTextArea.setEditable(false);
        undoManager = new UndoManager();
        inputTextArea.getDocument().addUndoableEditListener(e -> undoManager.addEdit(e.getEdit()));
        tokens = new ArrayList<>();
        errores = new ArrayList<>();
        
        inputTextArea.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            textoModificado();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            textoModificado();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            textoModificado();
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        inputTextArea = new javax.swing.JTextArea();
        infoLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        outputLabel = new javax.swing.JLabel();
        analizarBtn = new javax.swing.JButton();
        tokensBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        abrirMenu = new javax.swing.JMenu();
        guardarMenu = new javax.swing.JMenu();
        guardarComoMenu = new javax.swing.JMenu();
        nuevoMenu = new javax.swing.JMenu();
        copiarMenu = new javax.swing.JMenu();
        pegarMenu = new javax.swing.JMenu();
        deshacerMenu = new javax.swing.JMenu();
        rehacerMenu = new javax.swing.JMenu();
        acercaDeMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputTextArea.setColumns(20);
        inputTextArea.setRows(5);
        inputTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputTextAreaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(inputTextArea);

        infoLabel.setText("Ln 1 Col 1");

        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        jScrollPane2.setViewportView(outputTextArea);

        outputLabel.setText("Output");

        analizarBtn.setText("Analizador Sintáctico");

        tokensBtn.setText("Tokens");
        tokensBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tokensBtnMouseClicked(evt);
            }
        });

        abrirMenu.setText("Abrir");
        abrirMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(abrirMenu);

        guardarMenu.setText("Guardar");
        guardarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(guardarMenu);

        guardarComoMenu.setText("Guardar como");
        guardarComoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarComoMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(guardarComoMenu);

        nuevoMenu.setText("Nuevo");
        nuevoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevoMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(nuevoMenu);

        copiarMenu.setText("Copiar");
        copiarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                copiarMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(copiarMenu);

        pegarMenu.setText("Pegar");
        pegarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pegarMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(pegarMenu);

        deshacerMenu.setText("Deshacer");
        deshacerMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deshacerMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(deshacerMenu);

        rehacerMenu.setText("Rehacer");
        rehacerMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rehacerMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(rehacerMenu);

        acercaDeMenu.setText("Acerca de");
        acercaDeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaDeMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(acercaDeMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(outputLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                        .addComponent(tokensBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(analizarBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoLabel)
                    .addComponent(analizarBtn)
                    .addComponent(tokensBtn))
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirMenuMouseClicked
        if (cambiosSinGuardar) {
            int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Guardar cambios?",
                "Cambios no guardados",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if (opcion == JOptionPane.CANCEL_OPTION) {
                return;
            }

            if (opcion == JOptionPane.YES_OPTION) {
                guardarMenuMouseClicked(evt);
            }
        }
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Selecciona un archivo de texto");
        
        FileNameExtensionFilter filtro = new FileNameExtensionFilter(
            "Archivos de texto (*.txt, *.csv, *.log)", "txt", "csv", "log"
        );
        fileChooser.setFileFilter(filtro);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int resultado = fileChooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            rutaAbsolutaActual = archivoSeleccionado.getAbsolutePath();
            rutaActual = archivoSeleccionado.getPath();
            setTitle("Analizador Sintáctico - " + rutaActual);

            try (BufferedReader br = new BufferedReader(new FileReader(archivoSeleccionado))) {
                StringBuilder contenido = new StringBuilder();
                String linea;
                while ((linea = br.readLine()) != null) {
                    contenido.append(linea).append("\n");
                }
                inputTextArea.setText(contenido.toString());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage(),
                                              "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_abrirMenuMouseClicked

    private void guardarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMenuMouseClicked
        if (!rutaAbsolutaActual.isEmpty()) {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(rutaAbsolutaActual))) {
                writer.write(inputTextArea.getText());
                setTitle("Analizador Sintáctico - " + rutaActual + " (Guardado)");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
            cambiosSinGuardar = false;
        } else {
            guardarComoMenuMouseClicked(evt);
        }
    }//GEN-LAST:event_guardarMenuMouseClicked

    private void guardarComoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarComoMenuMouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar archivo como...");

        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivo de texto (*.txt)", "txt");
        fileChooser.setFileFilter(filtro);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int resultado = fileChooser.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = fileChooser.getSelectedFile();
            String rutaNuevoArchivo = archivoSeleccionado.getAbsolutePath();

            if (!rutaNuevoArchivo.toLowerCase().endsWith(".txt")) {
                archivoSeleccionado = new File(rutaNuevoArchivo + ".txt");
            }

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(archivoSeleccionado))) {
                writer.write(inputTextArea.getText());
                if(rutaAbsolutaActual.isEmpty()){
                    rutaAbsolutaActual = archivoSeleccionado.getAbsolutePath();
                    rutaActual = archivoSeleccionado.getPath(); 
                }
                setTitle("Analizador Sintáctico - " + rutaActual);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_guardarComoMenuMouseClicked

    private void nuevoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoMenuMouseClicked
        if (cambiosSinGuardar) {
            int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Guardar cambios?",
                "Cambios no guardados",
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if (opcion == JOptionPane.CANCEL_OPTION) {
                return;
            }

            if (opcion == JOptionPane.YES_OPTION) {
                guardarMenuMouseClicked(evt);
            }
        }

        inputTextArea.setText("");
        rutaAbsolutaActual = "";
        rutaActual = "";
        setTitle("Analizador Sintáctico - Nuevo Documento");
        cambiosSinGuardar = false;
    }//GEN-LAST:event_nuevoMenuMouseClicked

    private void acercaDeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaDeMenuMouseClicked
        String mensaje = """
                         ------------------------------------------------------
                         Nombre: Analizador Sintáctico
                         Descripción: Aplicación que permite 
                         analizar la estructura sintáctica 
                         de un texto a partir de los tokens 
                         generados por el lexer.
                         
                         Desarrollador:
                           - Mynor Daniel Morales (202331039)
                         
                         Fecha: 11/04/2025
                         ------------------------------------------------------""";

        JOptionPane.showMessageDialog(this, mensaje, "Acerca de", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_acercaDeMenuMouseClicked

    private void copiarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_copiarMenuMouseClicked
        String textoSeleccionado = inputTextArea.getSelectedText();
        
        if (textoSeleccionado != null && !textoSeleccionado.isEmpty()) {
            StringSelection selection = new StringSelection(textoSeleccionado);
            Clipboard portapapeles = Toolkit.getDefaultToolkit().getSystemClipboard();
            portapapeles.setContents(selection, null);
        } 
    }//GEN-LAST:event_copiarMenuMouseClicked

    private void pegarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pegarMenuMouseClicked
        Clipboard portapapeles = Toolkit.getDefaultToolkit().getSystemClipboard();

        try {
            String textoPegado = (String) portapapeles.getData(DataFlavor.stringFlavor);
            int posicionCursor = inputTextArea.getCaretPosition();
            if (inputTextArea.getSelectedText() != null) {
                inputTextArea.replaceSelection(textoPegado);
            } else {
                inputTextArea.insert(textoPegado, posicionCursor);
            }
        } catch (UnsupportedFlavorException | IOException e) {
            JOptionPane.showMessageDialog(this, "Error al pegar el texto: " + e.getMessage(),
                                          "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_pegarMenuMouseClicked

    private void deshacerMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deshacerMenuMouseClicked
        if (undoManager.canUndo()) {
            undoManager.undo();
        }
    }//GEN-LAST:event_deshacerMenuMouseClicked

    private void rehacerMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rehacerMenuMouseClicked
        if (undoManager.canRedo()) {
            undoManager.redo();
        }
    }//GEN-LAST:event_rehacerMenuMouseClicked

    private void tokensBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tokensBtnMouseClicked
        if (!hayErrores) {
            JDialog dialogo = new JDialog(this, "Tokens", true);
            dialogo.setSize(1000, 400);
            dialogo.setLocationRelativeTo(this);

            String[] columnas = {"Lexema", "Línea", "Columna", "Tipo"};

            String[][] datos = new String[tokens.size()][4];
            for (int i = 0; i < tokens.size(); i++) {
                Token t = tokens.get(i);
                datos[i][0] = t.getValor();
                datos[i][1] = String.valueOf(t.getLinea());
                datos[i][2] = String.valueOf(t.getColumna());
                datos[i][3] = t.getTipo().toString();
            }

            JTable tablaTokens = new JTable(datos, columnas);
            JScrollPane scrollPane = new JScrollPane(tablaTokens);
            
            dialogo.add(scrollPane);
            dialogo.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Hay errores en el texto.", 
                                          "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tokensBtnMouseClicked

    private void inputTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputTextAreaMouseClicked
        actualizarLabelInfo();
    }//GEN-LAST:event_inputTextAreaMouseClicked

    private void textoModificado() {
        setTitle("Analizador Sintáctico - " + rutaActual + " (Sin guardar)");
        cambiosSinGuardar = true;
        actualizarLabelInfo();
        tokenizar(inputTextArea.getText());
        verificarErrores();
        mostrarErrores();
    }
    
    private void actualizarLabelInfo(){
        int caretPosition = inputTextArea.getCaretPosition();
        try {
            int linea = inputTextArea.getLineOfOffset(caretPosition);
            int columna = caretPosition - inputTextArea.getLineStartOffset(linea);

            infoLabel.setText("Ln " + (linea + 1) + " Col: " + (columna + 1));
        } catch (BadLocationException e) {
        }
    }
    
    private void tokenizar(String input){
        tokens.clear();
        errores.clear();
        Lexer lexer = new Lexer(new StringReader(input));
        while(true) {
            try {
                Token token = lexer.yylex();
                if (token == null)
                    break;
                System.out.println(token.toString());
                tokens.add(token);
            } catch (IOException ex) {
            }
        }
    }
    
    private void verificarErrores(){
        for (Token token : tokens) {
            if(token.getTipo() == TipoToken.ERROR){
                hayErrores = true;
                errores.add(token);
            }else{
                hayErrores = false;
            }
        }
    }
    
    private void mostrarErrores(){
        StringBuilder erroresTexto = new StringBuilder();
        for (Token error : errores) {
            erroresTexto.append(error.toString()).append("\n");
        }
        outputTextArea.setText(erroresTexto.toString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu abrirMenu;
    private javax.swing.JMenu acercaDeMenu;
    private javax.swing.JButton analizarBtn;
    private javax.swing.JMenu copiarMenu;
    private javax.swing.JMenu deshacerMenu;
    private javax.swing.JMenu guardarComoMenu;
    private javax.swing.JMenu guardarMenu;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextArea inputTextArea;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu nuevoMenu;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JMenu pegarMenu;
    private javax.swing.JMenu rehacerMenu;
    private javax.swing.JButton tokensBtn;
    // End of variables declaration//GEN-END:variables
}
