package com.mynor.analizadorsintactico.lexer;

// DO NOT EDIT

import java.io.IOException;
import java.util.ArrayList;

// Generated by JFlex 1.9.1 http://jflex.de/
// source: lexer.jflex



@SuppressWarnings("fallthrough")
public class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    """
    \t\u0000\u0001\u0001\u0001\u0002\u0002\u0003\u0001\u0004\u0012\u0000\u0001\u0001\u0001\u0000\u0001\u0005\u0001\u0006\u0001\u0007\u0003\u0000\u0001\b\u0001\t\u0001
    \u0001\u000b\u0001\u0000\u0001\f\u0001\u0000\u0001\r\u0001\u000e\t\u000f\u0003\u0000\u0001\u0010\u0003\u0000\u0001\u0011\u0002\u0012\u0001\u0013\u0001\u0014\u0001\u0015\u0001\u0012\u0001\u0016\u0001\u0017\u0002\u0012\u0001\u0018\u0001\u0012\u0001\u0019\u0001\u0012\u0001\u001a\u0001\u0012\u0001\u001b\u0001\u001c\u0001\u001d\u0001\u001e\u0005\u0012\u0001\u0000\u0001\u001f\u0001\u0000\u0001 \u0001\u0012\u0001\u0000\u001a\u0012
    \u0000\u0001\u0003\u01a2\u0000\u0002\u0003\u00d6\u0000\u0100\u0003""";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    """
    \u0001\u0000\u0001\u0001\u0001\u0002\u0001\u0001\u0001\u0003\u0001\u0001\u0001\u0004\u0001\u0005\u0001\u0006\u0001\u0007\u0001\b\u0001\t\u0002
    \u0001\u000b\u0006\u0001\u0001\f\u0001\u0000\u0001\r\u0001\u0000\u0001\u000e\u0003\u0000\u0001\u000f\u0005\u0000\u0001\r\u0001\u0000\u0001\u0010\u0006\u0000\u0001\u0011\u0001\u0000\u0001\u0012\u0002\u0000\u0001\u0013\u0001\u0014\u0001\u0015\u0001\u0016\u0001\u0000\u0001\u0017""";

  private static int [] zzUnpackAction() {
    int [] result = new int[55];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\41\0\102\0\143\0\204\0\245\0\41\0\41"+
    "\0\41\0\41\0\41\0\306\0\41\0\347\0\41\0\u0108"+
    "\0\u0129\0\u014a\0\u016b\0\u018c\0\u01ad\0\41\0\143\0\41"+
    "\0\u01ce\0\245\0\u01ef\0\u0210\0\u0231\0\41\0\u0252\0\u0273"+
    "\0\u0294\0\u02b5\0\u02d6\0\143\0\u02f7\0\41\0\u0318\0\u0339"+
    "\0\u035a\0\u037b\0\u039c\0\u03bd\0\41\0\u03de\0\41\0\u03ff"+
    "\0\u0420\0\41\0\41\0\41\0\41\0\u0441\0\41";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[55];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    """
    \u0001\u0002\u0002\u0003\u0001\u0000\u0001\u0003\u0001\u0004\u0001\u0005\u0001\u0006\u0001\u0007\u0001\b\u0001\t\u0001
    \u0001\u000b\u0001\f\u0001\r\u0001\u000e\u0001\u000f\u0003\u0002\u0001\u0010\u0001\u0011\u0001\u0002\u0001\u0012\u0002\u0002\u0001\u0013\u0001\u0014\u0001\u0002\u0001\u0015\u0002\u0002\u0001\u0016"\u0000\u0002\u0003\u0001\u0000\u0001\u0003\u001c\u0000\u0002\u0017\u0001\u0000\u0002\u0017\u0001\u0018\u0019\u0017\u0001\u0019\u0001\u0017\u0002\u0005\u0003\u0000\u001c\u0005\f\u0000\u0001\u001a\u0001\u0000\u0002\u001a\u0001\u0000\u000e\u001a\f\u0000\u0001\u001b$\u0000\u0002\u000e*\u0000\u0001\u001c\u0018\u0000\u0001\u001d$\u0000\u0001\u001e\u0003\u0000\u0001\u001f"\u0000\u0001 \u0019\u0000\u0001!"\u0000\u0001"\u0004\u0000\u0001#\u0005\u0000\u0002\u0017\u0001\u0000\u0002\u0017\u0001$\u0019\u0017\u0001\u0019\u0001\u0017
    \u001b\u0001%\u0016\u001b\u0013\u0000\u0001&%\u0000\u0001'\u001f\u0000\u0001( \u0000\u0001)#\u0000\u0001*\u001a\u0000\u0001+*\u0000\u0001,\u0002\u0000
    \u001b\u0001%\u0002\u001b\u0001-\u0013\u001b\u001c\u0000\u0001.!\u0000\u0001/\u001c\u0000\u00010\u001b\u0000\u00011%\u0000\u00012\u001b\u0000\u00013 \u0000\u00014)\u0000\u00015\u0014\u0000\u00016,\u0000\u00017\u0003\u0000""";

  private static int [] zzUnpacktrans() {
    int [] result = new int[1122];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\4\1\5\11\1\1\1\11\1\1\1\11"+
    "\6\1\1\11\1\0\1\11\1\0\1\1\3\0\1\11"+
    "\5\0\1\1\1\0\1\11\6\0\1\11\1\0\1\11"+
    "\2\0\4\11\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[55];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */

private final ArrayList<Token> tokens = new ArrayList<>();
private final StringBuilder error = new StringBuilder();

public ArrayList<Token> analizar() {
    Token token;

        try {
            do {
                token = yylex();
                if (token != null) {
                    System.out.println(token.toString());
                    tokens.add(token);
                }
            } while (token != null && token.getTipo() != TipoToken.EOF);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    return tokens;
}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B', '\u000C', '\u0085', '\u2028', '\u2029' -> // fall through
              {
            yyline++;
            yycolumn = 0;
            zzR = false;
              }
        case '\r' -> // fall through
              {
            yyline++;
            yycolumn = 0;
            zzR = true;
              }
        case '\n' -> // fall through
              {
            if (zzR)
                zzR = false;
            else {
                yyline++;
                yycolumn = 0;
            }   }
        default -> // fall through
              {
            zzR = false;
            yycolumn += zzCharCount;
              }
        }
          // fall through
          // fall through
          // fall through
          // fall through
                }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                tokens.add(new Token("EOF", yyline+1, yycolumn+1, TipoToken.EOF));
                return null;
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
                Token tokenAnterior;
                
                if(!tokens.isEmpty()){
                    
                    tokenAnterior = tokens.get(tokens.size()-1);
                    
                    if(tokenAnterior.getTipo() == TipoToken.ERROR){
                        Token nuevoError = new Token(tokenAnterior.getValor() + yytext(), tokenAnterior.getLinea(), tokenAnterior.getColumna(), TipoToken.ERROR);
                        tokens.removeLast();
                        tokens.add(nuevoError);
                    }else{
                        tokens.add(new Token(yytext(), yyline + 1, yycolumn + 1, TipoToken.ERROR));
                    }
                }else{
                    tokens.add(new Token(yytext(), yyline + 1, yycolumn + 1, TipoToken.ERROR));
                }
                
                
                
            }
          // fall through
          case 24: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 25: break;
          case 3:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.COMENTARIO_LINEA));
            }
          // fall through
          case 26: break;
          case 4:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.PARENTESIS_APERTURA));
            }
          // fall through
          case 27: break;
          case 5:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.PARENTESIS_CIERRE));
            }
          // fall through
          case 28: break;
          case 6:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.MULTIPLICACION));
            }
          // fall through
          case 29: break;
          case 7:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.SUMA));
            }
          // fall through
          case 30: break;
          case 8:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.RESTA));
            }
          // fall through
          case 31: break;
          case 9:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.DIVISION));
            }
          // fall through
          case 32: break;
          case 10:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.NUMERO_ENTERO));
            }
          // fall through
          case 33: break;
          case 11:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.ASIGNACION));
            }
          // fall through
          case 34: break;
          case 12:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.POTENCIA));
            }
          // fall through
          case 35: break;
          case 13:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.LITERAL));
            }
          // fall through
          case 36: break;
          case 14:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.IDENTIFICADOR));
            }
          // fall through
          case 37: break;
          case 15:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.IF));
            }
          // fall through
          case 38: break;
          case 16:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.END));
            }
          // fall through
          case 39: break;
          case 17:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.COMENTARIO_BLOQUE));
            }
          // fall through
          case 40: break;
          case 18:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.INIT));
            }
          // fall through
          case 41: break;
          case 19:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.THEN));
            }
          // fall through
          case 42: break;
          case 20:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.TRUE));
            }
          // fall through
          case 43: break;
          case 21:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.FALSE));
            }
          // fall through
          case 44: break;
          case 22:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.PRINT));
            }
          // fall through
          case 45: break;
          case 23:
            { tokens.add(new Token(yytext(), yyline+1, yycolumn+1, TipoToken.REPEAT));
            }
          // fall through
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
